### ISSUE TITLE
cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (/stable-diffusion/comfy/samplers.py)

### ISSUE THREAD

**Issue by zba** [kijai/ComfyUI-DiffusersStableCascade#1]
latest comfyui main branch
some old version  of comfy  (before I pulled main) half-worked, but not current

**Comment by kijai** [comment]
I don't really understand how that error could be caused by this, comfy.samplers is not even used by the code...

**Comment by zba** [comment]
hm, it "self fixed" when I tried it today to get more logs :/
