### ISSUE TITLE
Errors regarding torch.Size, "expecting 64, got 16..." Ideas how to resolve?

### ISSUE THREAD

**Issue by LaughterOnWater** [kijai/ComfyUI-DiffusersStableCascade#13]
As posted on Reddit:

[https://www.reddit.com/r/comfyui/comments/1arh2du/stable_cascade_working_yesterday_not_working/](https://www.reddit.com/r/comfyui/comments/1arh2du/stable_cascade_working_yesterday_not_working/
)

Using this custom node:
[ComfyUI-DiffusersStableCascade](https://github.com/kijai/ComfyUI-DiffusersStableCascade)

With the workflow detailed here:
https://civitai.com/models/306016?modelVersionId=343529

Win10, 64GB RAM, 3090

The install went well. The workflow produces excellent images. I got embeddings to work. I couldn't figure out LoRAs. Started working on that today (after updating via ComfyUI Manager) and suddenly nothing works for Stable Cascade. So I went back to the original workflow from civitai, and that doesn't work either. Apparently changes have occurred in the stable cascade custom node that have changed parameters. I now see "SEGM_DETECTOR" has a red "X" next to it. (See image in original reddit post.)

I also get an error that pops up in a red box. (See code below.)

The linked reddit post above contains an image created with stable cascade and the Civitai workflow with prompt:
"A strawberry frog in a cranberry bog on a log in the fog."

I'd be grateful for ideas on how to fix this.

C

`Error occurred when executing DiffusersStableCascade:

Cannot load C:\Users\Chris\.cache\huggingface\hub\models--stabilityai--stable-cascade\snapshots\f2a84281d6f8db3c757195dd0c9a38dbdea90bb4\decoder because embedding.1.weight expected shape tensor(..., device='meta', size=(320, 64, 1, 1)), but got torch.Size([320, 16, 1, 1]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

File "D:\work\ai\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\work\ai\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\work\ai\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\work\ai\ComfyUI\custom_nodes\ComfyUI-DiffusersStableCascade\nodes.py", line 44, in process
self.decoder = StableCascadeDecoderPipeline.from_pretrained("stabilityai/stable-cascade", torch_dtype=torch.float16).to(device)
File "C:\Users\Chris\miniconda3\envs\sd\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
File "D:\work\ai\ComfyUI\custom_nodes\ComfyUI-DiffusersStableCascade\src\diffusers\src\diffusers\pipelines\pipeline_utils.py", line 1263, in from_pretrained
loaded_sub_model = load_sub_model(
File "D:\work\ai\ComfyUI\custom_nodes\ComfyUI-DiffusersStableCascade\src\diffusers\src\diffusers\pipelines\pipeline_utils.py", line 531, in load_sub_model
loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
File "C:\Users\Chris\miniconda3\envs\sd\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
File "D:\work\ai\ComfyUI\custom_nodes\ComfyUI-DiffusersStableCascade\src\diffusers\src\diffusers\models\modeling_utils.py", line 669, in from_pretrained
unexpected_keys = load_model_dict_into_meta(
File "D:\work\ai\ComfyUI\custom_nodes\ComfyUI-DiffusersStableCascade\src\diffusers\src\diffusers\models\modeling_utils.py", line 154, in load_model_dict_into_meta
raise ValueError(`

**Comment by rinaldop** [comment]
The same error for me.

**Comment by ErixStrong** [comment]
Yesterday it was working fine, but this morning I have the same error.

**Comment by kijai** [comment]
I suppose the cpu_offload I added doesn't work for everyone (works for me), I made it optional now, nothing else should have changed so it should fix this then.

**Comment by ErixStrong** [comment]
> So...not working yet?

Nope, not working...

**Comment by drymass2023** [comment]
same error for me.....awaiting @kijai to solve the issue, many thanks.

**Comment by Matticusnicholas** [comment]
I get the same error whether or not I use the ofload cpu option.

**Comment by cerarslan** [comment]
> I suppose the cpu_offload I added doesn't work for everyone (works for me), I made it optional now, nothing else should have changed so it should fix this then.

I updated the latest branch of custom nodes but still give me the same error. 

Error occurred when executing DiffusersStableCascade:

Cannot load C:\Users\charl\.cache\huggingface\hub\models--stabilityai--stable-cascade\snapshots\f2a84281d6f8db3c757195dd0c9a38dbdea90bb4\decoder because embedding.1.weight expected shape tensor(..., device='meta', size=(320, 64, 1, 1)), but got torch.Size([320, 16, 1, 1]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

**Comment by kijai** [comment]
I honestly don't know what I can do then, I haven't changed anything, since this is just using hugginface model download it's possible something changed in that end. I don't really think it's worth to spend too much time on this as I know Comfy himself is going to add official support for the models any day now.

**Comment by Matticusnicholas** [comment]
I spent all morning trying to get it to work :(

**Comment by RachidAR** [comment]
_Same error for me:_

ValueError: Cannot load /run/media/rachid/AItools/modelscache/hub/models--stabilityai--stable-cascade/snapshots/f2a84281d6f8db3c757195dd0c9a38dbdea90bb4/decoder because embedding.1.weight expected shape tensor(..., device='meta', size=(320, 64, 1, 1)), but got torch.Size([320, 16, 1, 1]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

**Comment by cerarslan** [comment]
> I honestly don't know what I can do then, I haven't changed anything and it's working fine for me, but since this is just using hugginface model download it's possible something changed in that end. I don't really think it's worth to spend too much time on this as I know Comfy himself is going to add official support for the models any day now

Okay, then sir. Thank you for all your effort

**Comment by topdeckg** [comment]
That's disappointing. I was hoping to try this but it looks like there's something that's bricking a lot of us.

**Comment by kijai** [comment]
Ok the issue is that they changed the model config: https://huggingface.co/stabilityai/stable-cascade/discussions/13#65ce2b43be38705ceecdd4bc

not sure how to compensate yet

**Comment by topdeckg** [comment]
Hopefully once you do have a solution it's as simple as updating the config file.

**Comment by rinaldop** [comment]
The extension for A1111 works like a charm in my computer.

**Comment by kijai** [comment]
Well it's hard for me to fix as I just can't reproduce the error, my config files are seemingly old and yet it works. But like I said, rather would wait for Comfy than use much time on this, if his SVD implementation is of any indication it's just gonna be way better than anything I could come up with.

**Comment by RachidAR** [comment]
I fixed it by modifying the config.json of the model. From '"c_in": 4' to '"in_channels": 4'. It works now.

**Comment by ErixStrong** [comment]
> I fixed it by modifying the config.json of the model. From '"c_in": 4' to '"in_channels": 4'. It works now.

What's the location of that file ?

**Comment by MattFog** [comment]
there's also a `models--stabilityai--stable-cascade-prior` in there that might be the previous version that worked

**Comment by MattFog** [comment]
For those of you that have trouble finding the directory (or getting bad results after changing those variables in the config.json)

1. open CMD

2. type "set HF_HOME" (this is for people that have set a custom repository for Hugging Face models.

2b. go to that directory in windows explorer, then go into ->\hub\models--stabilityai--stable-cascade\snapshots\f2a84281d6f8db3c757195dd0c9a38dbdea90bb4

2c. If you don't get a result on that, go to c:\[username]\.cache\huggingface\hub\models--stabilityai--stable-cascade\snapshots\f2a84281d6f8db3c757195dd0c9a38dbdea90bb4

3. in there, you'll find `config.json`. Copy it to make a backup, then change "c_in": 4' to '"in_channels": 4'

Then reload ComfyUI and try again.

My results are now unintellgible dogshit - not even images, just weird shapes.

It should also be noted that besides the `models--stabilityai--stable-cascade` folder, I also found `models--stabilityai--stable-cascade-prior` folder, which may or may not be the previous version that was working as expected. I'm going to noodle around a bit and then try to backup the current folder and rename the prior folder to the current and see if it works.

**Comment by LaughterOnWater** [comment]
It looks like 

> I fixed it by modifying the config.json of the model. From '"c_in": 4' to '"in_channels": 4'. It works now.

This actually worked for me. I had to update everything in manager, change it back to "c_in", restart again, then update everything again, then change it again to "in_channels", last time reboot comfyui. Now it works. 

I want to thank @kijai for all the support and actually creating this prequel custom node allowing us to check out everything in Stable Cascade!

**Comment by Matticusnicholas** [comment]
If you cant get it working there is a stable diffusion forge /auto 1111 extension for cascade

**Comment by MattFog** [comment]
I'm also seeing this error in the terminal window now:
3/6 [00:00<00:00,  6.23it/s]The config attributes {'c_in': 16} were passed to StableCascadeUnet, but are not expected and will be ignored. Please verify your config.json configuration file.
so we may have to change "c_in" to "in_channels"?

**Comment by theJamess** [comment]
Can confirm that the config.json update also corrects the issue in Ubuntu (path /home/user/.cache/huggingface/hub/models--stabilityai--stable-cascade/snapshots/f2a84281d6f8db3c757195dd0c9a38dbdea90bb4/decoder/config.json). A single restart of ComfyUI after the change is required.

**Comment by GalaxyTimeMachine** [comment]
The latest commits to the wuerstchen-v3 branch of diffusers is broken, and I got the same error as reported here this morning. The last working commit is a3dc21385b7386beb3dab3a9845962ede6765887
You can roll back using: `pip install --force-reinstall --no-deps git+https://github.com/huggingface/diffusers.git@a3dc21385b7386beb3dab3a9845962ede6765887`
This resolved the issue for me.

**Comment by LaughterOnWater** [comment]
I'm going to mark this as closed. We know the issue and have a temporary fix thanks to those in this thread. As @kijai pointed out, this was a quick look custom node that was meant as a temporary preview of what is likely to come in Comfy's core build. I'm just thankful for all the hard work that went into making this happen.

**Comment by isaac-mcfadyen** [comment]
Seems like the change that fixes things ("c_in" -> "in_channels") has been merged in the Diffusers branch, hopefully fixes this issue?

https://github.com/kashif/diffusers/commit/60efc49854ce28f37299c25eb00219862390f76d

**Comment by ErixStrong** [comment]
Hi Kijai, I installed the official Stable Cascade in Comfyui today and I compared the output images with the output images from your node. 

The image produced by your node are better (smoother) than the official version with the workflow that came with it. Can you tell me what setting I can change in both Ksamplers to produce a softer image like I had with your node ?

**Comment by cerarslan** [comment]
> Hi Kijai, I installed the official Stable Cascade in Comfyui today and I compared the output images with the output images from your node.
> 
> The image produced by your node are better (smoother) than the official version with the workflow that came with it. Can you tell me what setting I can change in both Ksamplers to produce a softer image like I had with your node ?

Hi mate. That's what's happening to me. I'm getting blurry images with native way. Did you fix the problem?

**Comment by kijai** [comment]
> Hi Kijai, I installed the official Stable Cascade in Comfyui today and I compared the output images with the output images from your node.
> 
> The image produced by your node are better (smoother) than the official version with the workflow that came with it. Can you tell me what setting I can change in both Ksamplers to produce a softer image like I had with your node ?

It's probably just the different scheduler, euler_a gives smoother results for example. So far I've liked ddpm with karras most, increasing steps and cfg also helps.

**Comment by cerarslan** [comment]
> Hi Kijai, I installed the official Stable Cascade in Comfyui today and I compared the output images with the output images from your node.
> 
> The image produced by your node are better (smoother) than the official version with the workflow that came with it. Can you tell me what setting I can change in both Ksamplers to produce a softer image like I had with your node ?


The reason keep getting blurry images is compression. Do not change the resolution in your workflow. This solves my issue mate

**Comment by ErixStrong** [comment]
_It's probably just the different scheduler, euler_a gives smoother results for example. So far I've liked ddpm with karras most, increasing steps and cfg also helps._

Thanks for your reply and the info. 

added: 

I'm not able to reproduce the output that I had with your node. I tried a lot of settings. 

If it's possible and you agree of course, it would be great if you could release a checkpoint with the settings you use in your node scripts to reproduce a similar output.

When I was doing photography, I did mainly face portrait and with your node, I was getting exactly the right sharpness, glow and skin colors to reproduce realistic portrait images, which I'm unable to reproduce with the release version for ComfyUI.

Thanks for your time.
