### ISSUE TITLE
How to use the locally downloaded files?

### ISSUE THREAD

**Issue by syddharth** [kijai/ComfyUI-DiffusersStableCascade#2]
While using the code provided here: https://github.com/Stability-AI/StableCascade, I downloaded a bunch of models files. Is it possible to use them?

**Comment by kijai** [comment]
Probably would be possible, but as Comfy is going to implement support for this model properly soon, I'm not going to develop this further than this. Currently it just uses whatever the default pipeline uses and autodownloads that.
