### ISSUE TITLE
There's a new custom trained model already on Civitai - possible to load that for generation?

### ISSUE THREAD

**Issue by CCpt5** [kijai/ComfyUI-DiffusersStableCascade#8]
Surprisingly there's already a trained model (beta/test) up on Civitai by a capable model maker here: https://civitai.com/models/306144/helloworld-stable-cascade-early-beta?modelVersionId=343656

Is there any way to load a model other than the base?

**Comment by camoody1** [comment]
You'll need to wait until Comfy releases his official support for Stable Cascade this weekend.
